name: aiohttp


volumes:
  postgres-data:


services:
  app:
    build:
      context: .
    env_file:
      - .env.docker
    depends_on:
      - db
    deploy:
      resources:
        limits:
          cpus: '0.8'
          memory: 70M
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 10
        window: 240s

  db:
    image: postgres:16
    volumes:
      - postgres-data:/var/lib/postgresql/data
    env_file:
      - .env.docker
    deploy:
      resources:
        limits:
          cpus: '0.2'
          memory: 30M
      restart_policy:
        condition: on-failure
        delay: 30s
        max_attempts: 5
        window: 150s
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped

  nginx:
    build: nginx
    ports:
      - '80:80'
    depends_on:
      - app
